###Make sure you use Playground mode
> File > Open in playground mode

###Make sure to allow cookies from colab.research.google.com

In Google Chrome:
>Settings > Advance > Privacy and security > Site Settings > Cookies and site data > Allow > Add >
colab.research.google.com

In [ ]:
#@title Welcome to the Geotab Bootcamp
#@markdown You can run Python code in the cells. Variables  created will be usable in future run cells  
print ("Welcome to Geotab Bootcamp")

Welcome to Geotab Bootcamp

In [ ]:
#@title Install modules
#@markdown We use the magic command %%capture to supress output
%%capture
!pip3 install pandas

 # Linux commands
 It is possible to run linux commands from a cell by prefixing with a !

In [ ]:
print ('Display working directory content:\n')
!ls
print ('\n\nDisplay working directory content after creation of a test directory:\n')
!mkdir test
!ls
print ('\n\nDisplay working directory detailed content after deleting the test directory:\n')
!rmdir test
!ls -l

Display working directory content:

sample_data


Display working directory content after creation of a test directory:

sample_data  test


Display working directory detailed content after deleting the test directory:

total 4
drwxr-xr-x 1 root root 4096 Jul 30 16:30 sample_data

# Files on the VM

On the left side menu you can view:
*   the table of content of this file (by clicking on the 3 bars icon)
*   code snippets (by clicking on the < > icon)
*   Files, where you can explore the folders of the virtual machine (by clicking on the folder icon)

#Connecting to BQ (BigQuery)
These steps will allow you to authenticate to BQ and then run a query from within Colab

In [1]:
#@title Authenticate
from google.colab import auth
_ = auth.authenticate_user()

In [2]:
#@title Google Big Query Client 
from google.cloud import bigquery
client = bigquery.Client(project='geotab-bootcamp')

#Running queries in BQ  
 We will run a sample query and save it to a dataframe

In [3]:
# 1. we first save the SQL as a String of characters
SQL = ''' 
              select *
              from `geotab-bootcamp.Dashboarding.Trips`
              limit 10
'''
# 2. then we will run SQL and save it in a Pandas dataframe
df = client.query(SQL).to_dataframe()
df.head(2)

   HardwareId  ...                      StopPoint
0           7  ...  POINT(-79.4693146 43.7601547)
1           7  ...    POINT(-79.46944 43.7603073)

[2 rows x 25 columns]